"use client";

import { useRouter } from "next/navigation";

import {
  Box,
  Button,
  Container,
  Typography,
  Grid,
  Card,
  CardContent,
  useTheme,
} from "@mui/material";
import { AutoAwesome, Speed, Devices, Security } from "@mui/icons-material";

import { motion } from "framer-motion";

export default function Home() {
  const router = useRouter();
  const theme = useTheme();
  const token = localStorage.getItem("token");

  const fadeIn = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.6 },
  };

  const features = [
    {
      icon: (
        <AutoAwesome sx={{ fontSize: 40, color: theme.palette.primary.main }} />
      ),
      title: "AI-Powered Design",
      description:
        "Create stunning websites instantly with our advanced AI technology",
    },
    {
      icon: <Speed sx={{ fontSize: 40, color: theme.palette.primary.main }} />,
      title: "Lightning Fast",
      description: "Generate complete websites in minutes, not hours or days",
    },
    {
      icon: (
        <Devices sx={{ fontSize: 40, color: theme.palette.primary.main }} />
      ),
      title: "Responsive Design",
      description: "Websites that look perfect on all devices, automatically",
    },
    {
      icon: (
        <Security sx={{ fontSize: 40, color: theme.palette.primary.main }} />
      ),
      title: "Secure & Reliable",
      description: "Built with security best practices and reliable hosting",
    },
  ];

  return (
    <Box
      sx={{
        minHeight: "100vh",
        background: "linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)",
        color: "white",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <Container maxWidth="lg" sx={{ py: 8, px: { xs: 2, sm: 3, md: 4 } }}>
        <Grid container spacing={6} alignItems="center">
          <Grid item xs={12} md={6}>
            <motion.div {...fadeIn}>
              <Typography
                variant="h1"
                sx={{
                  fontSize: { xs: "2.5rem", md: "3.5rem" },
                  fontWeight: 700,
                  lineHeight: 1.2,
                }}
              >
                Build Your Trading Website with AI
              </Typography>
              <Typography
                variant="h5"
                sx={{
                  mt: 2,
                  mb: 4,
                  opacity: 0.9,
                }}
              >
                Transform your trading business with a professional website,
                generated by AI in minutes
              </Typography>
              <Box sx={{ display: "flex", gap: 2 }}>
                <Button
                  variant="contained"
                  size="large"
                  onClick={() => {
                    if (token)
                      router.push("/AIWebsiteBuilders/template-selector");
                    else router.push("/AIWebsiteBuilders/auth/login");
                  }}
                  sx={{
                    bgcolor: "#fff",
                    color: theme.palette.primary.main,
                    "&:hover": {
                      bgcolor: "rgba(255,255,255,0.9)",
                    },
                  }}
                >
                  Get Started
                </Button>
                <Button
                  variant="outlined"
                  size="large"
                  onClick={() => router.push("/AIWebsiteBuilders/auth/login")}
                  sx={{
                    color: "#fff",
                    borderColor: "#fff",
                    "&:hover": {
                      borderColor: "rgba(255,255,255,0.9)",
                      bgcolor: "rgba(255,255,255,0.1)",
                    },
                  }}
                >
                  Sign In
                </Button>
              </Box>
            </motion.div>
          </Grid>
          <Grid item xs={12} md={6}>
            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.8 }}
            >
              <Box
                component="img"
                src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80"
                alt="Trading Dashboard"
                sx={{
                  width: "100%",
                  borderRadius: 4,
                  boxShadow: "0 20px 40px rgba(0,0,0,0.3)",
                }}
              />
            </motion.div>
          </Grid>
        </Grid>

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        >
          <Grid container spacing={4} sx={{ mt: 8 }}>
            {features.map((feature, index) => (
              <Grid item xs={12} sm={6} md={3} key={index}>
                <Card
                  sx={{
                    height: "100%",
                    bgcolor: "rgba(255,255,255,0.1)",
                    backdropFilter: "blur(10px)",
                    color: "white",
                  }}
                >
                  <CardContent sx={{ textAlign: "center", p: 2 }}>
                    <Box>{feature.icon}</Box>
                    <Typography variant="h6" sx={{ mt: 2 }}>
                      {feature.title}
                    </Typography>
                    <Typography variant="body2" sx={{ mt: 1, opacity: 0.8 }}>
                      {feature.description}
                    </Typography>
                  </CardContent>
                </Card>
              </Grid>
            ))}
          </Grid>
        </motion.div>
      </Container>
    </Box>
  );
}
