export const tradeSpecializations = [
  "Carpenter",
  "Plumber",
  "Electrician",
  "Painter",
  "Roofer",
  "HVAC Technician",
  "Mason",
  "Landscaper",
  "General Contractor",
  "Tile Installer",
  "Flooring Specialist",
  "Handyman",
  "Remodeler",
  "Home Inspector",
  "Welder",
  "Drywall Installer",
  "Fence Installer",
  "Concrete Specialist",
  "Other",
];
